### ISSUE TITLE
Generator RPC help

### ISSUE THREAD

**Issue by Jolg42** [iwehrman/node-connection-example#3]
Hi @iwehrman & @mcilroyc ,

I tried the [Generator RPC Example](https://github.com/iwehrman/generator-rpc-example) with this plugin (node-connection-example).

Everything is working but how is it possible to call the generator API from the browser now?
Like `getPhotoshopVersion` or `getPixmap`.

I didn't found any documentation on that, maybe I missed something?

**Comment by mcilroyc** [comment]
I commented on the [Google Group Topic](https://groups.google.com/forum/#!msg/adobe-generator-dev/zzUjc6V6tu8/Dy0LWVJMAAAJ).  Closing this bug in favor of that discussion.
